[package]
name = "servo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6" # or latest version
serde = { version = "1.0", features = ["derive"] }
lx16a-rs = { path = "../lx16a-rs" }